services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: rpg2d
      POSTGRES_USER: rpg2d
      POSTGRES_PASSWORD: rpg2d
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:9
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '127.0.0.1:8081:80'
    volumes:
      - pgadmin4-data:/var/lib/pgadmin

volumes:
  db-data:
  pgadmin4-data:
