name: CI

on:
  push:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup project
        uses: ./.github/actions/setup

      - name: Run lint
        run: pnpm lint

  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup project
        uses: ./.github/actions/setup

      - name: Run typecheck
        run: pnpm typecheck

      - name: Run unit tests
        run: pnpm test
